[GH-37] Implement slash command autocomplete
mattermost/mattermost-plugin-webex pull request #49
Opened 2020-10-12 17:25 UTC by GodlikePenguin

#### Summary

This commit adds autocomplete prompts for all of the subcommands offered by the plugin.
Adds a new `join` subcommand which is an alias for `/webex <@username>/<room id>. This was required as the Autocomplete library does not allow for a command to have both subcommands and arguments.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-plugin-webex/issues/37

2020-10-12 17:25 UTC, mattermod commented
Hello @GodlikePenguin,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-12 17:39 UTC, hanzei commented
@GodlikePenguin Could you please run `go mod tidy` and commit the changes in `go.sum` to fix CI?

2020-10-13 14:53 UTC, cpoile requested changes
Thank you @GodlikePenguin, this is great!
One suggestion for the help text, otherwise fantastic.

2020-10-13 14:53 UTC, cpoile commented on server/command.go
> +	join := model.NewAutocompleteData("join", "<room id>/<@username>", "Shares a link to a Webex meeting from a room id or a Mattermost username")
```suggestion
	join := model.NewAutocompleteData("join", "<room id>/<@username>", "Shares a link to a Webex meeting in <room id> or in <@username>'s meeting room")
```

2020-10-19 13:58 UTC, iomodo approved these changes
LGTM! Thanks @GodlikePenguin

2020-10-20 13:22 UTC, cpoile approved these changes
Nice, thanks @GodlikePenguin !

2020-10-22 01:41 UTC, DHaussermann approved these changes
Tested and passed
- Autocomplete is working as expected
- Tested on desktop and browser
- Confirmed join command is functional

LGTM! 

Huge thanks @GodlikePenguin for this enhancement!

2020-10-22 08:13 UTC, merged